kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: filesharekey1.0
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  resourceGroup: ubs
  storageAccount: aksdemokali
  shareName: sample1
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
