kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fileshare
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  resourceGroup: aksdemo
  storageAccount: aksdemostorage2
  shareName: sample1
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
